### ISSUE TITLE
TypeError: get_default_optimizer_params() got an unexpected keyword argument 'lr_factor_func'

### ISSUE THREAD

**Issue by witnessai** [JarintotionDin/ZiRaGroundingDINO#3]
Traceback (most recent call last):
  File "train_multidatasets.py", line 573, in <module>
    launch(
  File "/home/user/anaconda3/envs/zira_py3.8/lib/python3.8/site-packages/detectron2/engine/launch.py", line 67, in launch
    mp.spawn(
  File "/home/user/anaconda3/envs/zira_py3.8/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/user/anaconda3/envs/zira_py3.8/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/home/user/anaconda3/envs/zira_py3.8/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/zira_py3.8/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/user/anaconda3/envs/zira_py3.8/lib/python3.8/site-packages/detectron2/engine/launch.py", line 126, in _distributed_worker
    main_func(*args)
  File "/home/user/morjio/projects/detection/ZiRaGroundingDINO/train_multidatasets.py", line 493, in main
    do_train(args, cfg)
  File "/home/user/morjio/projects/detection/ZiRaGroundingDINO/train_multidatasets.py", line 398, in do_train
    optim = instantiate(cfg.optimizer)
  File "/home/user/anaconda3/envs/zira_py3.8/lib/python3.8/site-packages/detectron2/config/instantiate.py", line 61, in instantiate
    cfg = {k: instantiate(v) for k, v in cfg.items()}
  File "/home/user/anaconda3/envs/zira_py3.8/lib/python3.8/site-packages/detectron2/config/instantiate.py", line 61, in <dictcomp>
    cfg = {k: instantiate(v) for k, v in cfg.items()}
  File "/home/user/anaconda3/envs/zira_py3.8/lib/python3.8/site-packages/detectron2/config/instantiate.py", line 77, in instantiate
    return cls(**cfg)
TypeError: get_default_optimizer_params() got an unexpected keyword argument 'lr_factor_func'

**Comment by JarintotionDin** [comment]
I just tried my code and found nothing wrong. It may be an issue of inconsistent dependency versions. What is the version of your Detectron2.

**Comment by witnessai** [comment]
Thank you for your reply. According to the requirements in requirements.txt, the Detectron2 version is 0.6. Could you please show the versions of all your Python libraries (such as the torch version, etc.)? Thank you very much.

**Comment by witnessai** [comment]
Additionally, could you also mention the version of Python you are using? Although this isn't very important, it may affect the versions of the Python packages you install.

**Comment by JarintotionDin** [comment]
Thank you for your suggestion. We has show all the Python libraries in requirements.txt, and provide recommendation using Python 3.9 in readme.

**Comment by witnessai** [comment]
Thank you very much for your reply. The command `sh train_odinw13_zira.sh` executed successfully, and it seems that the environment installation was successful.

**Comment by gaoyingjay** [comment]
@witnessai 可以看下你的配置文件吗，d2 0.6最多只支持torch1.10啊

**Comment by wansdd** [comment]
I have meet this problem, my torch vision is 1.10.0+cu111. My detectron2 version is  0.6,  compiled locally.  So how I can tackle this issue? thanks
